image: python:3.12-alpine

before_script:
    - pip install -r requirements.txt
stages:
    - test
    - style
pylint:
    stage: style
    script: 
        - pylint --fail-under=7 main.py
    artifacts:
        untracked: false
        when: on_success
        expire_in: 30 days
pycodestyle:
    stage: style
    script: 
        - pycodestyle main.py
    artifacts:
        untracked: false
        when: on_success
        expire_in: 30 days