# Generated by Django 5.0 on 2024-02-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niknem',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_codes.account'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_image', models.ImageField(upload_to='')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_codes.account')),
            ],
        ),
    ]
