# Generated by Django 5.0 on 2024-02-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_codes', '0002_niknem_account_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='new_image',
            new_name='image',
        ),
    ]
